#!/usr/bin/env zsh


pw=$(find ~/.password-store/* -type f | grep -Eo '[^/]*/[^/]*.gpg'  | sed 's/.gpg//g' | bemenu -l 10)
[ -z $pw ] && exit 1

pass -c $pw
notify-send 'Note' "Copied $pw to clipboard"
