[general]
live_config_reload = true


[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
normal.family = "Hack Nerd Font Mono"
normal.style = "Regular"

bold.family = "Hack Nerd Font Mono"
bold.style = "Bold"

italic.family = "Hack Nerd Font Mono"
italic.style = "Italic"

bold_italic.family = "Hack Nerd Font Mono"
bold_italic.style = "Bold Italic"

size = 13.0
